-- ROMANCE (10 inserts)
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Orgulho e Preconceito', 'Jane Austen', 'T. Egerton', 1813, 'Romance', 'orgulho_preconceito.jpg', 5, 20000000, 29.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Dom Casmurro', 'Machado de Assis', 'Editora Garnier', 1899, 'Romance', 'dom_casmurro.jpg', 5, 150000, 24.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Culpa é das Estrelas', 'John Green', 'Dutton Books', 2012, 'Romance', 'culpa_estrelas.jpg', 5, 23000000, 34.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Morro dos Ventos Uivantes', 'Emily Brontë', 'Thomas Cautley Newby', 1847, 'Romance', 'morro_ventos.jpg', 5, 10000000, 27.80);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Anna Kariênina', 'Liev Tolstói', 'The Russian Messenger', 1877, 'Romance', 'anna_karenina.jpg', 5, 15000000, 32.40);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Como Eu Era Antes de Você', 'Jojo Moyes', 'Penguin Books', 2012, 'Romance', 'como_eu_era.jpg', 4, 8000000, 31.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Eleanor & Park', 'Rainbow Rowell', 'St. Martin''s Press', 2013, 'Romance', 'eleanor_park.jpg', 4, 5000000, 28.75);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Persuasão', 'Jane Austen', 'John Murray', 1817, 'Romance', 'persuasao.jpg', 5, 5000000, 26.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Amor nos Tempos do Cólera', 'Gabriel García Márquez', 'Editora Oveja Negra', 1985, 'Romance', 'amor_tempos_colera.jpg', 5, 20000000, 35.20);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Emma', 'Jane Austen', 'John Murray', 1815, 'Romance', 'emma.jpg', 5, 10000000, 25.60);

-- AÇÃO (10 inserts)
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Caçador de Pipas', 'Khaled Hosseini', 'Riverhead Books', 2003, 'Ação', 'cacador_pipas.jpg', 5, 32000000, 39.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Código Da Vinci', 'Dan Brown', 'Doubleday', 2003, 'Ação', 'codigo_davinci.jpg', 4, 80000000, 42.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Hobbit', 'J.R.R. Tolkien', 'Allen & Unwin', 1937, 'Ação', 'hobbit.jpg', 5, 100000000, 37.80);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Jurassic Park', 'Michael Crichton', 'Alfred A. Knopf', 1990, 'Ação', 'jurassic_park.jpg', 5, 15000000, 45.20);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Senhor dos Anéis', 'J.R.R. Tolkien', 'Allen & Unwin', 1954, 'Ação', 'senhor_aneis.jpg', 5, 150000000, 49.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Jogos Vorazes', 'Suzanne Collins', 'Scholastic', 2008, 'Ação', 'jogos_vorazes.jpg', 5, 100000000, 36.70);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Silmarillion', 'J.R.R. Tolkien', 'Allen & Unwin', 1977, 'Ação', 'silmarillion.jpg', 4, 5000000, 41.30);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Bússola de Ouro', 'Philip Pullman', 'Scholastic', 1995, 'Ação', 'bussola_ouro.jpg', 5, 15000000, 33.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('As Crônicas de Nárnia', 'C.S. Lewis', 'Geoffrey Bles', 1950, 'Ação', 'narnia.jpg', 5, 120000000, 38.40);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Guia do Mochileiro das Galáxias', 'Douglas Adams', 'Pan Books', 1979, 'Ação', 'guia_mochileiro.jpg', 5, 20000000, 29.90);

-- MISTÉRIO (10 inserts)
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Nome da Rosa', 'Umberto Eco', 'Bompiani', 1980, 'Mistério', 'nome_rosa.jpg', 5, 50000000, 44.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Sombra do Vento', 'Carlos Ruiz Zafón', 'Editora Planeta', 2001, 'Mistério', 'sombra_vento.jpg', 5, 15000000, 39.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Código Da Vinci', 'Dan Brown', 'Doubleday', 2003, 'Mistério', 'codigo_davinci_misterio.jpg', 4, 80000000, 42.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Silêncio dos Inocentes', 'Thomas Harris', 'St. Martin''s Press', 1988, 'Mistério', 'silencio_inocentes.jpg', 5, 20000000, 36.80);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Garota Exemplar', 'Gillian Flynn', 'Crown Publishing', 2012, 'Mistério', 'garota_exemplar.jpg', 5, 15000000, 34.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Assassinato no Expresso do Oriente', 'Agatha Christie', 'Collins Crime Club', 1934, 'Mistério', 'expresso_oriente.jpg', 5, 50000000, 28.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Psicopata Americano', 'Bret Easton Ellis', 'Vintage', 1991, 'Mistério', 'psicopata_americano.jpg', 4, 10000000, 31.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Iluminado', 'Stephen King', 'Doubleday', 1977, 'Mistério', 'iluminado.jpg', 5, 10000000, 37.20);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Colecionador de Ossos', 'Jeffery Deaver', 'Viking Press', 1997, 'Mistério', 'colecionador_ossos.jpg', 4, 8000000, 32.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Paciente Silenciosa', 'Alex Michaelides', 'Celadon Books', 2019, 'Mistério', 'paciente_silenciosa.jpg', 5, 5000000, 45.90);

-- SUSPENSE (10 inserts)
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('It: A Coisa', 'Stephen King', 'Viking Press', 1986, 'Suspense', 'it.jpg', 4, 10000000, 49.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Iluminado', 'Stephen King', 'Doubleday', 1977, 'Suspense', 'iluminado_suspense.jpg', 5, 10000000, 42.70);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Silêncio dos Inocentes', 'Thomas Harris', 'St. Martin''s Press', 1988, 'Suspense', 'silencio_inocentes_suspense.jpg', 5, 20000000, 38.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Garota Exemplar', 'Gillian Flynn', 'Crown Publishing', 2012, 'Suspense', 'garota_exemplar_suspense.jpg', 5, 15000000, 34.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Psicopata Americano', 'Bret Easton Ellis', 'Vintage', 1991, 'Suspense', 'psicopata_americano_suspense.jpg', 4, 10000000, 36.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Colecionador de Ossos', 'Jeffery Deaver', 'Viking Press', 1997, 'Suspense', 'colecionador_ossos_suspense.jpg', 4, 8000000, 32.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Paciente Silenciosa', 'Alex Michaelides', 'Celadon Books', 2019, 'Suspense', 'paciente_silenciosa_suspense.jpg', 5, 5000000, 45.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Homem de Giz', 'C.J. Tudor', 'Crown Publishing', 2018, 'Suspense', 'homem_giz.jpg', 4, 3000000, 39.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Antes de Dormir', 'S.J. Watson', 'HarperCollins', 2011, 'Suspense', 'antes_dormir.jpg', 4, 7000000, 31.20);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Mulher na Janela', 'A.J. Finn', 'William Morrow', 2018, 'Suspense', 'mulher_janela.jpg', 4, 4000000, 37.80);

-- DRAMA (10 inserts)
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('1984', 'George Orwell', 'Secker & Warburg', 1949, 'Drama', '1984.jpg', 5, 2000000, 27.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Crime e Castigo', 'Fiódor Dostoiévski', 'The Russian Messenger', 1866, 'Drama', 'crime_castigo.jpg', 5, 10000000, 32.40);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Apanhador no Campo de Centeio', 'J.D. Salinger', 'Little, Brown', 1951, 'Drama', 'apanhador_centeio.jpg', 5, 65000000, 29.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Revolução dos Bichos', 'George Orwell', 'Secker & Warburg', 1945, 'Drama', 'revolucao_bichos.jpg', 5, 25000000, 22.50);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Sol é para Todos', 'Harper Lee', 'J. B. Lippincott & Co.', 1960, 'Drama', 'sol_para_todos.jpg', 5, 40000000, 34.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'Tipografia Nacional', 1881, 'Drama', 'bras_cubas.jpg', 5, 800000, 19.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Estrangeiro', 'Albert Camus', 'Gallimard', 1942, 'Drama', 'estrangeiro.jpg', 4, 10000000, 26.80);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('Ensaio sobre a Cegueira', 'José Saramago', 'Caminho', 1995, 'Drama', 'cegueira.jpg', 5, 15000000, 31.90);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('A Metamorfose', 'Franz Kafka', 'Kurt Wolff Verlag', 1915, 'Drama', 'metamorfose.jpg', 4, 15000000, 23.70);
INSERT INTO book (name, author, publisher, yearPublished, category, image, evaluation, bookspurchased, price) VALUES ('O Retrato de Dorian Gray', 'Oscar Wilde', 'Lippincott''s', 1890, 'Drama', 'dorian_gray.jpg', 5, 20000000, 28.50);