INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('Shadow Slave', 'Guiltythree', 'WebNovel', 2022, 'Ação', 'https://i1.sndcdn.com/artworks-KlzGzGAyG7Bo8CYl-o9LyAw-t500x500.jpg', 4, 53100000, 84.99, 'Sunny, um jovem pobre, é escolhido pelo Feitiço do Pesadelo e ganha poderes sobrenaturais. Transportado para um mundo em ruínas, enfrenta monstros e outros Despertos, mas seu poder tem um efeito colateral mortal.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('Childhood Friend of The Zenith', 'Woobi Ram', 'NovelPia', 2021, 'Ação', 'https://slimeread.com/_next/image?url=https%3A%2F%2Fblack.slimeread.com%2Fcovers%2Famigo-de-infancia-da-zenite.jpeg&w=384&q=100', 4, 42153977, 50.00, 'Gu Yangchun, um humano demoníaco arrependido, regride no tempo até conhecer Wi Seol-ah. Decidido a viver em paz, ele vê seu passado sombrio voltar para assombrá-lo.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('O Hobbit', 'J. R. R. Tolkien', 'George Allen & Unwin', 1937, 'Ação', 'https://upload.wikimedia.org/wikipedia/pt/thumb/7/72/The_Hobbit_Cover.JPG/230px-The_Hobbit_Cover.JPG', 5, 100000000, 35.92, 'Bilbo Bolseiro, um hobbit pacato, é arrastado por Gandalf e anões em uma jornada para roubar o tesouro de Smaug, o dragão. Uma aventura que mudará sua vida para sempre.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('A Grande Solidão', 'Kristin Hannah', 'Arqueiro', 2018, 'Drama', 'https://m.media-amazon.com/images/I/61SahnaFnEL._AC_UF1000,1000_QL80_.jpg', 5, 2562, 40.00, 'Um veterano do Vietnã leva a família para o Alasca em busca de recomeço, mas o inverno rigoroso revela traumas perigosos que ameaçam sua família.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('Um Lugar Bem Longe Daqui', 'Delia Owens', 'Intrínseca', 2019, 'Drama', 'https://m.media-amazon.com/images/I/41rJfBLXMbL._SY445_SX342_.jpg', 5, 11819, 70.00, 'Kya, a "Menina do Brejo", cresce isolada nos pântanos até se tornar suspeita de um crime. História de sobrevivência, amor e mistério na natureza.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('O Sol é Para Todos', 'Harper Lee', 'José Olympio', 1960, 'Drama', 'https://m.media-amazon.com/images/I/91WKPd60P4L._SY342_.jpg', 5, 14108, 40.00, 'Nos anos 1930, Scout testemunha seu pai defender um homem negro injustamente acusado, em um comovente retrato do racismo no sul dos EUA.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('O Jardim das Borboletas', 'Dot Hutchison', 'Planeta', 2017, 'Suspense', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaI8v_gMY4qyp1Jrp00a0wtCr5qzMIw0vWXh7UTsjuCxtPjlMk', 5, 4542, 68.08, 'Jovens mulheres são sequestradas por um psicopata conhecido como Jardineiro e mantidas em um jardim sinistro. Uma sobrevivente relata os horrores ao FBI.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('Misery: Louca Obsessão', 'Stephen King', 'Suma', 2014, 'Suspense', 'https://m.media-amazon.com/images/I/91ocgbfq55L._SY342_.jpg', 5, 7723, 60.00, 'Um escritor acidentado é mantido refém por uma fã obcecada que o força a reescrever sua história favorita sob ameaças violentas.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('A Essência do Mal', 'Luca D''Andrea', 'Intrínseca', 2018, 'Suspense', 'https://books.google.com.br/books/publisher/content?id=5ShaDwAAQBAJ&hl=pt-BR&pg=PA1&img=1&zoom=3&bul=1&sig=ACfU3U3KLWy7UcIrVDlyu7YJlnhuOP5oPw&w=1280', 4, 1247, 34.90, 'Um documentarista investiga assassinatos brutais nos Alpes italianos e desencadeia uma força sombria ligada ao passado da região.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('A Hipótese do Amor', 'Ali Hazelwood', 'Editorial Arqueiro', 2022, 'Romance', 'https://m.media-amazon.com/images/I/81LTEfXYgcL.jpg', 5, 1500, 45.03, 'Olive Smith, uma cientista cética sobre o amor, inventa um namoro falso e acaba beijando um desconhecido - agora precisa sustentar a mentira.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('O Lado Feio Do Amor', 'Colleen Hoover', 'Editorial Record', 2014, 'Romance', 'https://m.media-amazon.com/images/I/8151svfx-9L._UF894,1000_QL80_.jpg', 5, 47992, 46.72, 'Tate Collins descobre os lados sombrios do amor quando se envolve em um relacionamento sem compromisso, onde sentimentos se tornam armadilhas perigosas.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('The Regressor and The Blind Saint', 'Papapa', 'Novelpia', 2021, 'Romance', 'https://cdn.novelupdates.com/images/2022/04/The-Regressor-and-the-Blind-Saint.jpg', 4, 6736, 34.99, 'Após ser salvo por uma santa, Vera, um criminoso arrependido, regressa ao passado. Determinado a redimir-se, ele usa seu poder para protegê-la e garantir que ela nunca caia na miséria novamente.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('Five Nights at Freddy´s: Pavores de Fazbear 1: Mergulho Na Escuridão', 'Elley Cooper, Scott Cawthon', 'Intrínseca', 2024, 'Mistério', 'https://m.media-amazon.com/images/I/81ICtgMY0DL._UF894,1000_QL80_.jpg', 5, 10000, 37.40, 'Oswald entra numa piscina de bolinhas e viaja para o passado da Pizzaria Freddy Fazbear´s, onde um coelho maligno começa a assombrá-lo.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('Lord of The Mysteries', 'Cuttlefish That Loves Diving', 'Qidian', 2018, 'Mistério', 'https://blogsenai.s3.us-east-2.amazonaws.com/blog-samuel/src/img/lord-of-the-mysteries.jpg', 5, 52600000, 120.00, 'Em um mundo steampunk místico, Klein Moretti ascende como "O Louco" do tarô através de poções sobrenaturais, desvendando conspirações entre tecnologia e ocultismo.');

INSERT INTO books (name, author, publisher, yearPublished, category, image, evaluation, booksPurchased, price, description) VALUES ('O Chamado de Cthulhu', 'H.P. Lovecraft', 'Necronomicon Press', 1928, 'Mistério', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1593081778i/54256506.jpg', 5, 50000, 29.90, 'Um investigador desvenda um culto ancestral que adora uma entidade cósmica adormecida no fundo do oceano, despertando horrores além da compreensão humana.');